### ISSUE TITLE
Error al aplicar parches

### ISSUE THREAD

**Issue by Zefirott** [Glowtranslations/StellaGlowESP#13]
Podrias revisar la manera y detallar como aplicas los parches, tanto para la demo 1.1 como para el juego 1.1 debido a que trate de varias formas y siempre me daba error de archivos como la carpeta no tiene permisos para, falta un archivo (stellademoesp.cia o stellatemp.cxi) los archivos .cxi los probe extrayendolos tanto con GodMode9 como con Decrypt9 y me dio error con los dos metodos ademas lo hice desde el disco C y desactivando el antivirus y nada sobre la version USA del juego tanto del demo como de la version completa en un windows xp 32 bits y en 8.1 64 bits. por favor revisar se agaradece. Zefirott

**Comment by Darkmet98** [comment]
@Zefirott ¿estás usando un backup de tu juego original?

**Comment by Zefirott** [comment]
Use la versión USA descargada desde ***** que seria la version digital imagino y la demo usa original descargada a mi consola desde EShop que tambien es digital, no creo que sea por que debo usar windows 7??? De esas 2 versiones extraje el archivo .CXI. Entiendo que a lo mejor la version completa diera error por que uno no sabe que modificacion le hacen a los juegos de la ****** pero la demo es muy extraño por que la baje original y tampoco funciono.

**Comment by Darkmet98** [comment]
@Zefirott glowtranslations no apoya la pirateria y el parcheador no funciona con archivos que no sean originales.
